### ISSUE TITLE
Export variables with prefix

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/slugify-value#2]
## Current situation

```yaml
- uses: rlespinasse/slugify-value@v1.x
   with:
     key: EXISTING_ENV_VAR
```

Will make available

- `EXISTING_ENV_VAR_SLUG`
- `EXISTING_ENV_VAR_SLUG_CS`
- `EXISTING_ENV_VAR_SLUG_URL`
- `EXISTING_ENV_VAR_SLUG_URL_CS`
 
 ## Proposition
 
 In addition to the current mode, we  add a new input `prefix`
 
```yaml
- uses: rlespinasse/slugify-value@v1.x
   with:
     key: EXISTING_ENV_VAR
     value: CI_
```

Will make available

- `CI_EXISTING_ENV_VAR`
- `CI_EXISTING_ENV_VAR_SLUG`
- `CI_EXISTING_ENV_VAR_SLUG_CS`
- `CI_EXISTING_ENV_VAR_SLUG_URL`
- `CI_EXISTING_ENV_VAR_SLUG_URL_CS`
