### ISSUE TITLE
Enable configuration of the slug size

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/slugify-value#6]
Currently limited to 63 characters, with an option, we could define another limit or no limit at all.

```yaml
- uses: rlespinasse/slugify-value@v1
   with:
     key: KEY_NAME
     value: value_to_slugify
     slug-maxlength: 63
     # or
     slug-maxlength: nolimit
```

Related to rlespinasse/github-slug-action#87
